//! `xtask report`: the human-facing surface of the whole repo.
//!
//! Writes `results/REPORT.md` (the index: per-fixture table, a first-class
//! known-limitations section, and the token comparison) and
//! `results/details/<fixture>.md` (the actual before/after content per
//! fixture, since a fidelity percentage on its own doesn't tell anyone
//! whether the tree is worth sending to a model).

use anyhow::Result;
use std::fmt::Write as _;
use std::path::Path;

use unrender::render::{compare, render};
use unrender::{build_tree, emit, grid::Grid, strip_ansi};
use unrender_eval::score::compute_score;
use unrender_eval::{discover, Fixture};

use crate::tokens::TokenCache;

/// Below this, a fixture is named in the known-limitations section rather
/// than left to be noticed by scrolling the table.
const LIMITATION_THRESHOLD: f64 = 0.6;

struct Encodings {
    raw: String,
    plain: String,
    compact: String,
    toon: String,
    json: String,
}

fn build_encodings(bytes: &[u8]) -> Encodings {
    let tree = build_tree(bytes);
    let raw = String::from_utf8_lossy(bytes).to_string();
    let plain = strip_ansi(&raw);
    let mut compact = String::new();
    emit::compact(&tree, 0, &mut compact);
    let mut toon = String::new();
    emit::toon(&tree, 0, &mut toon);
    let json = serde_json::to_string_pretty(&tree).unwrap();
    Encodings {
        raw,
        plain,
        compact,
        toon,
        json,
    }
}

struct TokenRow {
    raw: Option<usize>,
    plain: Option<usize>,
    compact: Option<usize>,
    toon: Option<usize>,
    json: Option<usize>,
}

fn count_all(cache: &mut TokenCache, enc: &Encodings) -> Result<TokenRow> {
    Ok(TokenRow {
        raw: cache.get_or_count(&enc.raw)?,
        plain: cache.get_or_count(&enc.plain)?,
        compact: cache.get_or_count(&enc.compact)?,
        toon: cache.get_or_count(&enc.toon)?,
        json: cache.get_or_count(&enc.json)?,
    })
}

fn fmt_tok(n: Option<usize>) -> String {
    n.map(|v| v.to_string()).unwrap_or_else(|| "-".to_string())
}

/// Which of the structured encodings is cheapest, if we know both. Never
/// asserts TOON wins -- the spike's own data shows a tree's shape can flip
/// this, and `json` sometimes beats plain text sending raw ANSI too little
/// structure to compress.
fn cheapest(toon: Option<usize>, json: Option<usize>) -> &'static str {
    match (toon, json) {
        (Some(t), Some(j)) if t <= j => "toon",
        (Some(_), Some(_)) => "json",
        (Some(_), None) => "toon",
        (None, Some(_)) => "json",
        (None, None) => "-",
    }
}

pub fn run(root: &Path) -> Result<()> {
    let fixtures = discover(root);
    anyhow::ensure!(
        !fixtures.is_empty(),
        "no fixtures found under {}/fixtures",
        root.display()
    );

    let mut cache = TokenCache::load(root)?;
    let have_key = std::env::var("ANTHROPIC_API_KEY").is_ok();
    if !have_key {
        eprintln!(
            "note: ANTHROPIC_API_KEY not set -- uncached fixtures will show \
             token counts as '-' rather than a wrong number from a proxy tokenizer"
        );
    }

    std::fs::create_dir_all(root.join("results/details"))?;

    let mut report = String::new();
    writeln!(report, "# unrender — results\n")?;
    writeln!(
        report,
        "Auto-generated by `cargo run -p xtask -- report`. Do not hand-edit; \
         re-run the command instead.\n"
    )?;
    writeln!(
        report,
        "Token counts are real Claude token counts (`claude-opus-5`, via \
         `POST /v1/messages/count_tokens`), cached by content hash in \
         `results/tokens.json`. A `-` means the content changed and no \
         `ANTHROPIC_API_KEY` was available to count it -- never a guess from \
         a different model's tokenizer.\n"
    )?;

    writeln!(
        report,
        "| fixture | truth | fidelity | recall | role% | IoU | raw | plain | compact | toon | json | cheapest |"
    )?;
    writeln!(
        report,
        "|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|"
    )?;

    let mut limitations = Vec::new();
    let mut toon_wins = 0usize;
    let mut json_wins = 0usize;
    let mut scored = 0usize;

    for f in &fixtures {
        let bytes = f.read_ansi()?;
        let original = Grid::from_ansi_autosize(&bytes);
        let tree = build_tree(&bytes);
        let rebuilt = render(&tree);
        let fid = compare(&original, &rebuilt);

        let enc = build_encodings(&bytes);
        let tok = count_all(&mut cache, &enc)?;

        let truth_source = f.truth_source();
        let (recall, role_pct, iou) = if let Some(truth) = f.read_truth() {
            let s = compute_score(&bytes, &truth)?;
            (Some(s.recall()), Some(s.role_agreement()), Some(s.mean_iou))
        } else {
            (None, None, None)
        };

        writeln!(
            report,
            "| [{}](details/{}.md) | {} | {:.0}% | {} | {} | {} | {} | {} | {} | {} | {} | {} |",
            f.name,
            f.name.replace('/', "-"),
            truth_source,
            fid.content_match * 100.0,
            recall
                .map(|v| format!("{:.0}%", v * 100.0))
                .unwrap_or_else(|| "-".into()),
            role_pct
                .map(|v| format!("{:.0}%", v * 100.0))
                .unwrap_or_else(|| "-".into()),
            iou.map(|v| format!("{v:.2}")).unwrap_or_else(|| "-".into()),
            fmt_tok(tok.raw),
            fmt_tok(tok.plain),
            fmt_tok(tok.compact),
            fmt_tok(tok.toon),
            fmt_tok(tok.json),
            cheapest(tok.toon, tok.json),
        )?;

        if let (Some(t), Some(j)) = (tok.toon, tok.json) {
            scored += 1;
            if t <= j {
                toon_wins += 1;
            } else {
                json_wins += 1;
            }
        }

        if fid.content_match < LIMITATION_THRESHOLD {
            limitations.push(format!(
                "- **{}** — {:.0}% content preservation. See [details/{}.md](details/{}.md).",
                f.name,
                fid.content_match * 100.0,
                f.name.replace('/', "-"),
                f.name.replace('/', "-")
            ));
        }

        write_detail(root, f, &enc, &fid, recall, role_pct, iou)?;
    }

    writeln!(report, "\n## Known limitations\n")?;
    if limitations.is_empty() {
        writeln!(
            report,
            "None below the {:.0}% content-preservation threshold right now.",
            LIMITATION_THRESHOLD * 100.0
        )?;
    } else {
        writeln!(
            report,
            "Fixtures below {:.0}% content preservation, named rather than left for someone \
             to notice by scrolling the table:\n",
            LIMITATION_THRESHOLD * 100.0
        )?;
        for l in &limitations {
            writeln!(report, "{l}")?;
        }
    }

    writeln!(report, "\n## Token efficiency\n")?;
    if scored > 0 {
        writeln!(
            report,
            "TOON was cheapest on {toon_wins}/{scored} fixtures where both were counted; \
             JSON on {json_wins}/{scored}. Not asserted in advance -- a tree's shape can flip \
             which wins, and the numbers above are what actually happened, not a claim."
        )?;
    } else {
        writeln!(
            report,
            "No fixtures have both `toon` and `json` counted yet."
        )?;
    }

    std::fs::write(root.join("results/REPORT.md"), report)?;
    cache.save(root)?;
    println!("wrote results/REPORT.md and results/details/*.md");
    Ok(())
}

fn write_detail(
    root: &Path,
    f: &Fixture,
    enc: &Encodings,
    fid: &unrender::render::Fidelity,
    recall: Option<f64>,
    role_pct: Option<f64>,
    iou: Option<f64>,
) -> Result<()> {
    let mut d = String::new();
    writeln!(d, "# {}\n", f.name)?;
    writeln!(d, "[← back to REPORT.md](../REPORT.md)\n")?;
    writeln!(d, "truth source: `{}`\n", f.truth_source())?;
    writeln!(
        d,
        "content preservation: **{:.0}%** (chrome-excluded; {} non-blank content cells)",
        fid.content_match * 100.0,
        fid.nonblank_cells - fid.chrome_cells
    )?;
    if let (Some(r), Some(role), Some(i)) = (recall, role_pct, iou) {
        writeln!(
            d,
            "\nstructural: recall {:.0}%, role agreement {:.0}%, mean IoU {:.2}",
            r * 100.0,
            role * 100.0,
            i
        )?;
    }

    writeln!(d, "\n## Before (color-stripped)\n")?;
    writeln!(d, "```\n{}\n```\n", enc.plain.trim_end())?;

    writeln!(d, "## After — compact\n")?;
    writeln!(d, "```\n{}\n```\n", enc.compact.trim_end())?;

    writeln!(d, "## After — toon\n")?;
    writeln!(d, "```\n{}\n```\n", enc.toon.trim_end())?;

    writeln!(
        d,
        "<details><summary>After — json</summary>\n\n```json\n{}\n```\n\n</details>\n",
        enc.json.trim_end()
    )?;

    let path = root
        .join("results/details")
        .join(format!("{}.md", f.name.replace('/', "-")));
    std::fs::write(path, d)?;
    Ok(())
}
